### ISSUE TITLE
sha3: add cShake

### ISSUE THREAD

**Issue by niluxv** [RustCrypto/hashes#182]
Add cShake, as described in [\[1\]][nistpaper] to the `sha3` crate (it is a standard way to input a diversifier to shake separate from the normal input).

\[1\]: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf

[nistpaper]: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf

**Comment by tarcieri** [comment]
@newpavlov do you think we should track this in #1?

**Comment by newpavlov** [comment]
I thought it will be implemented as small helper functions on top of the existing Shake types, but reading the specification a bit more carefully, I guess we can consider it as an additional algorithm. There is an annoying property that if `n` and `s` are empty, then cShake is equal to the usual Shake which uses `0x1f` suffix for padding, otherwise in addition to prepending to data encoded parameter strings it also uses `0x04` suffix. So assuming that we want to keep streaming capabilities, we will have to keep the padding variant in hasher states.
