### ISSUE TITLE
How to use Shake128

### ISSUE THREAD

**Issue by zwq1792966796** [RustCrypto/hashes#205]
let mut hasher = Shake128::new();
    hasher.update(b"123");
    let result = hasher.finalize();
    println!("shake128 :  Result: {:x}", result);

   Shake128 have no new function,no update function ,Can you give me an example.
   Thank you

**Comment by newpavlov** [comment]
All functionality is exposed via traits defined in the [`digest`](https://docs.rs/digest/) crate, so you have to import relevant traits to access their methods. SHAKE128 is XOF, so instead of result you first get reader and then extract result of necessary length.

```rust
use sha3::{Shake128, digest::{Update, ExtendableOutput, XofReader}};

let mut hasher = Shake128::default();
hasher.update(b"123");
let mut reader = hasher.finalize_xof();
let mut buf = [0u8; 32];
reader.read(&mut buf);
println!("{:?}", buf);
```

You can convert the byte array to hex encoding using the [`hex`](https://docs.rs/hex/) crate.
