### ISSUE TITLE
[sha2] TODO: replace after sha2-asm rework

### ISSUE THREAD

**Issue by mattcollier** [RustCrypto/hashes#213]
Is there an issue to track this TODO? Can some additional description be added?

https://github.com/RustCrypto/hashes/blob/39a55cf35a4282648298586193d6f8384f30869e/sha2/src/sha512.rs#L235-L236

**Comment by tarcieri** [comment]
@newpavlov ?

**Comment by newpavlov** [comment]
The idea was to change signatures of the asm crates to accept `&[[u8; 128]]` instead of the current single-block `&[u8; 128]`. Effectively it's a workaround around the noalias LLVM bug, currently after each block was processed the state is saved needlessly, instead of staying in registers. The only workaround which I have found was to copy state to a local variable and work with it, thus the need for the multi-block compression.

The ASM crates currently have a low priority for us and potential performance improvements are quite small, so I probably simply will remove this comment.
