### ISSUE TITLE
Add the digest of the empty hash as a constant

### ISSUE THREAD

**Issue by ndmitchell** [RustCrypto/hashes#259]
It would be useful if there were constants representing the digest of the empty slice, for example:

```
const Sha1::EMPTY : GenericArray<u8, Sha1::OutputSize> = ...
```

These constants tend to come up somewhat often in code, and it's useful if they are constants, so avoid computing them in the code, and avoid trying to hash them etc.

**Comment by newpavlov** [comment]
Why exactly do you need hash of an empty slice? Honestly, I never encountered a use-case where it would've been useful.

We would like to constify out trait implementations eventually, but the Rust language is still quite under-developed in this area. Meanwhile, I don't think we should add such ad-hoc constants to our crates. I think a better solution for you would be to add such constant to your code using the [`arr!`](https://docs.rs/generic-array/0.14.4/generic_array/macro.arr.html) macro and test correctness of such value in module tests.

**Comment by tarcieri** [comment]
AFAIK it's not possible to make constants with `GenericArray` right now?

**Comment by ndmitchell** [comment]
My use case is I'm working with a library which needs to upload files. Sometimes those files are on disk (great, I hash them) and sometimes they are placeholder files (need to use the empty hash). While I can do `digest(&[])` that seems a bit inefficient, since this is a fairly hot path, and I hope the value of the constant is the same every time. I could do `arr!` or a normal Rust array, but then I have to write a test that it's correct. It would be much easier to obtain the result from the library, rather than defining it myself.

As to whether it's a `GenericArray` or a `[u8; SHA1_SIZE]` I'm ambivalent. The latter would be slightly better for my use case, but either works for me.

**Comment by newpavlov** [comment]
@tarcieri 
>AFAIK it's not possible to make constants with GenericArray right now?

Ah, I thought `arr!` would work in `const` contexts. One possible workaround:
```rust
const FOO: GenericArray<u32, U3> = unsafe {
    std::mem::transmute([1u32, 2, 3])
};
```
It's far from ideal, but should do the job.

@ndmitchell
I don't think it's a sufficient motivation for adding such constants to our crates. Don't forget that we have many algorithms (including keyed and variable-size hashes) and strive for consistent API across them. Since I think your use-case is relatively uncommon and it looks like you work only with one hash function, I think it will be better to introduce this constant in your code.
