### ISSUE TITLE
sha2 v0.9.X appears to break no_std

### ISSUE THREAD

**Issue by gram-signal** [RustCrypto/hashes#302]
I've got a Cargo.toml with:

```
[dependencies]
sha2 = {version = "0.8", default-features = false}
```

that compiles a `#![no_std]` binary just fine.  It utilizes solely this function:

```
use sha2::{Digest, Sha256};
...
let code_hash: [u8; 32] = Sha256::digest(code).into();
```

If I switch the dependency version in Cargo.toml from "0.8" to "0.9", I get:

```
error[E0152]: found duplicate lang item `panic_impl`
  --> src/main.rs:39:5
   |
39 |     fn panic(_info: &PanicInfo) -> ! {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: the lang item is first defined in crate `std` (which `sha2` depends on)
   = note: first definition in `std` loaded from /home/xxxx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/powerpc-unknown-linux-gnu/lib/libstd-43f07ba4ad95e1f9.so, /home/xxxx/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/powerpc-unknown-linux-gnu/lib/libstd-43f07ba4ad95e1f9.rlib
   = note: second definition in the local crate (`yyyy`)
```

I'm compiling with:  `cargo +nightly build --target=powerpc-unknown-linux-gnu --release`

**Comment by tarcieri** [comment]
Note that we test `no_std` builds as part of CI:

https://github.com/RustCrypto/hashes/blob/master/.github/workflows/sha2.yml#L20-L39

Have you tried to make a minimal reproduction of this, or is it part of a larger project? I just created a simple test project which includes the following in Cargo.toml:

```
[dependencies]
sha2 = { version = "0.9", default-features = false }
```

It compiles fine for me:

```
$ cargo build --target thumbv7em-none-eabi
[...]
   Compiling sha2 v0.9.5
[...]
    Finished dev [unoptimized + debuginfo] target(s) in 8.22s
```

If you're using it in the context of a larger project, it's possible that one of your other dependencies (e.g. build/dev dependencies) is activating the `std` feature of `sha2` v0.9, and v0.8 works because Cargo treats it as a separate crate.

The "best" fix there, IMO, is to switch to `resolver = "2"` in your workspace's Cargo.toml, but note that's MSRV 1.51.

**Comment by gram-signal** [comment]
You're 100% correct - a non-powerpc target was pulling in the sha2-with-std.  Switching to resolver=2 fixed this, thanks!
