### ISSUE TITLE
Intel SGX enclave core dumped after update from sha2 v0.9.6 -> v0.9.8

### ISSUE THREAD

**Issue by haerdib** [RustCrypto/hashes#321]
In our project we're using an intel sgx enclave (no_std environment). When updating `sha2` from `v0.9.6` (which is working perfectly) to `0.9.8` we're getting an `Illegal instruction (core dumped)`. It happened on two different enclaves, one on  Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-151-generic x86_64) and one on Ubuntu 20.04 (also x86_64), with different intel driver and sgxsdk versions. 

Is it possible to fix this? If you need more information I'll gladly provide them.

**Comment by tarcieri** [comment]
The main new feature that was added is AVX2 with automatic runtime detection via CPUID.

CPUID is not available from within an SGX enclave, however we disable CPUID checks if `target_env = "sgx"` (deferring to compile-time checks):

https://github.com/RustCrypto/utils/blob/fd95867/cpufeatures/src/x86.rs#L20-L22

Are you compiling an SGX enclave in such a way that `target_env` isn't set to `"sgx"` somehow? Otherwise this would indicate some sort of a bug in our code to bypass the CPUID check in an SGX context.

**Comment by haerdib** [comment]
Hm. I think we'd have run into problems alot earlier if the target_env variable was not set to sgx. But let me investiage on this matter a little bit deeper to rule this possibility out completely.  I'll report back on that, thanks for the fast answer.

**Comment by tarcieri** [comment]
Another thing you can do is explicitly enable AVX2 using target flags:

```
RUSTFLAGS="-Ctarget-feature=+avx2"
```

That will bypass the runtime check entirely.

**Comment by clangenb** [comment]
`target_env` is not set to `sgx` in our case because we compile with cargo and not with environment aware `xargo`. Hence, I guess we need ot incorporate said rustflag.

**Comment by haerdib** [comment]
> Another thing you can do is explicitly enable AVX2 using target flags:
> 
> ```
> RUSTFLAGS="-Ctarget-feature=+avx2"
> ```
> 
> That will bypass the runtime check entirely.

With this rustflag enabled it's working perfectly. Thank you very much for your help!
