### ISSUE TITLE
The speed of calculating in rust seems like not as fast as in Node.

### ISSUE THREAD

**Issue by XLearner** [RustCrypto/hashes#453]
Hi Maintainer, I wanted to use the sha2::Sha256 to do "Proof of Work" with rust and transformed Rust code to "WebAssembly" for the web page finally. So I did some tests separately in Node and rust. However, the result is unsatisfying. Node is much faster than Rust. I am curious about what reason could be leading to the disparity in the speed?

Here is my testing code:
[demo-node.txt](https://github.com/RustCrypto/hashes/files/10820370/demo-node.txt)
[demo-rs.txt](https://github.com/RustCrypto/hashes/files/10820373/demo-rs.txt)

**Comment by tarcieri** [comment]
It sounds like you're comparing Node's `crypto` module, which IIUC is a wrapper for the optimized ASM implementations in OpenSSL, against a pure Rust implementation of SHA-2 compiled to WebAssembly.

This isn't really a fair comparison, because you're comparing hand-optimized architecture-specific assembly to WASM, which is interpreted/JITed.

Some fair comparisons would be:

- RustCrypto WASM vs JavaScript
- RustCrypto WASI vs Node.js

**Comment by burdges** [comment]
Is it worth having benchmarks with and without `-C codegen-units=1`?  It'd avoid regressions from cross crate stuff like https://docs.rs/blake2/latest/blake2/type.Blake2b.html
