### ISSUE TITLE
No tag for sha-1 v0.10.1

### ISSUE THREAD

**Issue by paolobarbolini** [RustCrypto/hashes#576]
Weirdly the repository contains tags for v0.10.0 and v0.10.3, but the latest version is v0.10.1 :man_shrugging:.

Because the crates.io release doesn't contain `.cargo_vcs_info.json`, most likely because of `cargo publish --allow-dirty`, it is NOT currently possible to verify that the crates.io release can be reproduced from the contents of the repository using completely automated steps.

**Comment by newpavlov** [comment]
`sha-1 v0.10.1` was published as part of fixing #438. It was done out of tree (since `master` tracks `sha1`), so no tag was created. We probably can amend this by branching from a `master` commit with date closest to the date of publishing and reproducing the crate changes (mostly adding the deprecation notice).

**Comment by newpavlov** [comment]
Added [`sha-1-v0.10.1`](https://github.com/RustCrypto/hashes/tree/sha-1-v0.10.1) tag. `cargo googles` did not find any issues with it (though it did not like `digest` and `crypto-common`, we probably should look into it later).
