### ISSUE TITLE
impl AsyncWrite

### ISSUE THREAD

**Issue by elpiel** [RustCrypto/hashes#92]
It would be nice to be able to use an algorithm with `async_std` which uses AsyncWrite for that purpose.

Maybe we can add it as a feature flag?

**Comment by newpavlov** [comment]
I don't think async stuff makes much sense for CPU-bound algorithms. You probably want to offload such computations to a thread pool, so I don't think it should be done as part of RustCrypto crates.

**Comment by elpiel** [comment]
Maybe something like the `Compat` extensions for `futures` will do the trick. The idea is to be able to use a hasher with `async_std::io::copy` for example. To be able to get the hash of a whole file but use the async function instead. This way people can use the `async_std::fs::File` and `async_std::io::copy` with the hasher.

**Comment by newpavlov** [comment]
If my understanding is correct I think it can be done without any problems in a separate crate. Right now I don't think this should be done as part of the RustCrypto project, since we deliberately aim to keep API surface minimal (e.g. we don't have any convenience methods for converting hash results into hex representation).

**Comment by elpiel** [comment]
Make sense actually, will look into that.
